const cityToIATA: Record<string, string> = {
  // Israeli airports
  "תל אביב": "TLV",
  "tel aviv": "TLV",
  "אילת": "ETH",
  "eilat": "ETH",
  // Europe
  "לונדון": "LHR",
  "london": "LHR",
  "פריז": "CDG",
  "paris": "CDG",
  "ברלין": "BER",
  "berlin": "BER",
  "רומא": "FCO",
  "rome": "FCO",
  "ברצלונה": "BCN",
  "barcelona": "BCN",
  "מדריד": "MAD",
  "madrid": "MAD",
  "אמסטרדם": "AMS",
  "amsterdam": "AMS",
  "פראג": "PRG",
  "prague": "PRG",
  "וינה": "VIE",
  "vienna": "VIE",
  "אתונה": "ATH",
  "athens": "ATH",
  "ליסבון": "LIS",
  "lisbon": "LIS",
  "בודפשט": "BUD",
  "budapest": "BUD",
  "איסטנבול": "IST",
  "istanbul": "IST",
  "מילאנו": "MXP",
  "milan": "MXP",
  "מינכן": "MUC",
  "munich": "MUC",
  "ורשה": "WAW",
  "warsaw": "WAW",
  "קופנהגן": "CPH",
  "copenhagen": "CPH",
  "דבלין": "DUB",
  "dublin": "DUB",
  // Asia
  "טוקיו": "NRT",
  "tokyo": "NRT",
  "בנגקוק": "BKK",
  "bangkok": "BKK",
  "סינגפור": "SIN",
  "singapore": "SIN",
  "הונג קונג": "HKG",
  "hong kong": "HKG",
  "סיאול": "ICN",
  "seoul": "ICN",
  "בייג'ינג": "PEK",
  "beijing": "PEK",
  // Americas
  "ניו יורק": "JFK",
  "new york": "JFK",
  "לוס אנג'לס": "LAX",
  "los angeles": "LAX",
  "מיאמי": "MIA",
  "miami": "MIA",
  "טורונטו": "YYZ",
  "toronto": "YYZ",
  "קנקון": "CUN",
  "cancun": "CUN",
  // Africa & Middle East
  "דובאי": "DXB",
  "dubai": "DXB",
  "מרקש": "RAK",
  "marrakech": "RAK",
  "קהיר": "CAI",
  "cairo": "CAI",
};

export function getIATACode(city: string): string | null {
  const normalized = city.trim().toLowerCase();
  return cityToIATA[normalized] || null;
}

export const ORIGIN_AIRPORT = "TLV";
